# Generated by Django 6.0.1 on 2026-01-07 10:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('total_scans', models.IntegerField(default=0)),
                ('fmd_detected', models.IntegerField(default=0)),
                ('healthy_cattle', models.IntegerField(default=0)),
                ('not_cow_detected', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'System Statistics',
                'verbose_name_plural': 'System Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='cattle_images/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending Analysis'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('healthy', 'Healthy'), ('fmd', 'FMD Detected'), ('not_cow', 'Not a Cow'), ('inconclusive', 'Inconclusive')], max_length=20, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('animal_id', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by_admin', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detection Record',
                'verbose_name_plural': 'Detection Records',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('farm_name', models.CharField(default='Simba Farms', max_length=100)),
                ('location', models.CharField(default='Ibanda District', max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
