# Generated by Django 6.0.1 on 2026-02-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_alter_detection_result_alter_detection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('vet', 'Veterinary Doctor')], default='farmer', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
