# Generated by Django 6.0.1 on 2026-03-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_new_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='vet_notes',
            field=models.TextField(blank=True, help_text="Vet's response / reason for rejection"),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='administered_by',
            field=models.CharField(blank=True, help_text='Vet name or clinic', max_length=200),
        ),
    ]
