# Generated by Django 6.0.1 on 2026-02-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_userprofile_license_number_userprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='receive_fmd_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('vet', 'Veterinary Doctor'), ('admin', 'Administrator')], default='farmer', max_length=10),
        ),
    ]
