# Generated by Django 6.0.1 on 2026-03-11 07:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_alter_appointment_vet_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='vet_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
