# Generated by Django 6.0.1 on 2026-03-11 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_alter_appointment_id_alter_appointment_vet_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='animal_id',
        ),
    ]
