# Generated by Django 6.0.1 on 2026-03-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_detection_bbox_fields'),
        ('detection', '0006_remove_userprofile_receive_fmd_notifications_and_more'),
    ]

    operations = [
    ]
