# Generated by Django 6.0.1 on 2026-04-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0007_marketlisting_marketcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('upload', 'New Upload'), ('fmd_alert', 'FMD Alert'), ('analysis_done', 'Analysis Complete'), ('vet_registration', 'New Vet Registration')], max_length=20),
        ),
    ]
