# Generated by Django 6.0.1 on 2026-03-07 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_add_bounding_boxes'),
        ('detection', '0007_merge_20260304_1856'),
    ]

    operations = [
    ]
