# Generated by Django 6.0.1 on 2026-03-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0008_merge_20260307_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='annotated_image',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='result_label',
        ),
        migrations.AlterField(
            model_name='detection',
            name='result',
            field=models.CharField(blank=True, choices=[('healthy', 'Foot and mouth disease not detected'), ('fmd', 'Foot and mouth disease detected'), ('not_cow', 'Not a Cow')], max_length=20, null=True),
        ),
    ]
